baseURL = "https://lctt-aws-basics.netlify.app"
languageCode = "en-us"
title = "AWS Basics"
theme = "hugo-theme-relearn"

canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]
<<<<<<< HEAD

=======
  editURL = "https://github.com/LaunchCodeEducation/aws-basics/edit/master/content/"

[[menu.shortcuts]]
  name = "Contributing to this Project"
  url = "/contributing"
  weight = 99998
>>>>>>> 86de56e (enabled github issues for the project)

