baseURL = "https://lctt-aws-basics.netlify.app"
languageCode = "en-us"
title = "AWS Basics"
theme = "hugo-theme-relearn"

[outputs]
  home = ["HTML", "RSS", "JSON"]

canonifyURLs = true

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]


